Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "vodka")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "gin")
Ingredient.create(name: "tonic")
Ingredient.create(name: "coca-cola")
Ingredient.create(name: "soda water")
